package com.HealthCare.HealthCare.patient.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;

/**
 * Entity representing a patient in the HealthCare system.
 * <p>
 * This entity includes all essential patient information:
 * - Personal details: firstName, lastName, dob, gender
 * - Status and department
 * - Visit history: lastVisitFrom, lastVisitTo
 * - Contact and insurance details
 * - Auto-generated patient ID and QR code
 * </p>
 * <p>
 * The QR code stores a Base64 string representing encoded patient info for scanning.
 * </p>
 */
@Entity
@Table(name = "patients")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Patient {

    /**
     * Unique identifier for the patient. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long patientId;

    /**
     * First name of the patient. Cannot be null.
     */
    @Column(nullable = false)
    private String firstName;

    /**
     * Last name of the patient. Cannot be null.
     */
    @Column(nullable = false)
    private String lastName;

    /**
     * Date of birth of the patient.
     */
    private LocalDate dob;

    /**
     * Gender of the patient (e.g., Male, Female, Other).
     */
    private String gender;

    /**
     * Current status of the patient (e.g., Active, Inactive).
     */
    private String status;

    /**
     * Department associated with the patient (e.g., Cardiology, Neurology).
     */
    private String department;

    /**
     * Start date of the last visit.
     */
    private LocalDate lastVisitFrom;

    /**
     * End date of the last visit.
     */
    private LocalDate lastVisitTo;

    /**
     * Residential address of the patient.
     */
    private String address;

    /**
     * Contact number of the patient.
     */
    private String contactNumber;


    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "insuranceProvider", column = @Column(name = "insurance_provider")),
            @AttributeOverride(name = "policyNumber", column = @Column(name = "policy_number"))
    })
    private InsurancePayment insurancePayment;

    @Lob
    private String qrCode;
}

